# Generated by Django 5.2.7 on 2025-12-04 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellow_id', models.CharField(help_text='Unique identifier, e.g., FEL-2024-001', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('degree_field', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('training_completed', models.BooleanField(default=False, help_text='Has completed the initial Land of Goshen training.')),
                ('fellowship_start_date', models.DateField()),
                ('fellowship_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellows', to='locations.sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fellow_id'],
            },
        ),
    ]
