# Generated by Django 5.2.7 on 2025-12-14 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fellow',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Fellow', 'verbose_name_plural': 'Fellows'},
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='fellow_id',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fellow',
            name='assigned_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellows', to='locations.sector'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='training_completed',
            field=models.BooleanField(default=False),
        ),
    ]
