# Generated by Django 5.2.7 on 2025-12-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0002_alter_fellow_options_remove_fellow_created_at_and_more'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='The professional mentor supervising this fellow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellows', to='mentors.mentor'),
        ),
    ]
