# Generated by Django 5.2.7 on 2025-12-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fellows', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('village_name', models.CharField(max_length=100)),
                ('number_of_farmers_trained', models.IntegerField()),
                ('training_topic', models.CharField(help_text='e.g., Mulching, Crop Rotation, Soil Conservation', max_length=255)),
                ('training_method', models.CharField(choices=[('demonstration', 'Demonstration'), ('field_visit', 'Field Visit'), ('group_session', 'Group Session'), ('workshop', 'Workshop')], max_length=50)),
                ('duration_hours', models.FloatField(help_text='Duration of the training session in hours (e.g., 2.5)')),
                ('challenges_notes', models.TextField(blank=True, null=True)),
                ('success_stories', models.TextField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='training_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fellows.fellow')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_activities', to='locations.sector')),
            ],
            options={
                'verbose_name_plural': 'Training Activities',
                'ordering': ['-date', 'sector__name'],
            },
        ),
    ]
