# Generated by Django 5.2.7 on 2025-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingactivity',
            name='mentor_comments',
            field=models.TextField(blank=True, help_text='Feedback provided by the assigned Mentor.', null=True),
        ),
        migrations.AddField(
            model_name='trainingactivity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REVISION', 'Needs Revision')], default='PENDING', help_text='The current approval status of this report.', max_length=20),
        ),
    ]
