# Generated by Django 5.2.7 on 2025-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_trainingactivity_mentor_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingactivity',
            name='is_resubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
