# Generated by Django 5.2.7 on 2026-01-06 16:02

import activities.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_trainingactivity_is_resubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingactivity',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='trainingactivity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Format: HH:MM:SS (e.g., 02:30:00 for 2 hours and 30 mins)'),
        ),
        migrations.AlterField(
            model_name='trainingactivity',
            name='date',
            field=models.DateField(validators=[activities.models.validate_not_future]),
        ),
        migrations.AlterField(
            model_name='trainingactivity',
            name='number_of_farmers_trained',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='You must train at least one farmer.')]),
        ),
    ]
