# Generated by Django 5.2.7 on 2026-01-06 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_trainingactivity_duration_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingactivity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingactivity',
            name='verified_village',
            field=models.CharField(blank=True, help_text='Standardized village name confirmed by Mentor upon approval.', max_length=100, null=True),
        ),
    ]
