# Generated by Django 5.2.7 on 2026-01-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_trainingactivity_approved_by_and_more'),
    ]

    operations = [
    ]
