# Generated by Django 5.2.7 on 2025-12-04 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('coordinator', 'Program Coordinator'), ('fellow', 'Fellow (Field Officer)'), ('viewer', 'Donor/Partner Viewer')], default='fellow', help_text='The role determines system access and permissions.', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('organization', models.CharField(blank=True, help_text='For viewer/donor profiles.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
