# Generated by Django 5.2.7 on 2025-12-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COORDINATOR', 'Coordinator'), ('FELLOW', 'Fellow'), ('MENTOR', 'Mentor'), ('VIEWER', 'Viewer')], default='FELLOW', max_length=20),
        ),
    ]
