# Generated by Django 5.2.7 on 2026-01-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.sector')),
            ],
            options={
                'ordering': ['sector__name', 'name'],
                'unique_together': {('name', 'sector')},
            },
        ),
    ]
